import { z } from 'zod';

/**
 * Schema for `globals.yaml` — the per-machine registry of globally-installed
 * Claude Code plugins, MCP servers, and (eventually) hooks at user scope.
 *
 * Phase B (suit v0.7 / wardrobe v4): introduces the snapshot format. Phase D
 * wires the resolver to consume this so outfits/modes/accessories can target
 * globals by name.
 *
 * v0.8 extends the registry to additional harnesses (currently codex). Plugin
 * and MCP entries gain an optional `harness` discriminator; entries omit it for
 * backwards compatibility with v0.7 registries (which were claude-code only).
 *
 * The file is generated by `suit-build sync-globals`, committed to wardrobe
 * via PR, and is a per-machine artifact — different developers will have
 * different `globals.yaml` shapes.
 */

const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const SEMVER_RE = /^\d+\.\d+\.\d+(-[\w.]+)?(\+[\w.]+)?$/;

const PluginSourceEnum = z.enum([
  'claude-code-marketplace',
  'manual',
  'github',
  // v0.8 codex sources. Codex marketplaces map to `codex-marketplace` when the
  // entry was synced from a known marketplace; `manual` covers the rest.
  'codex-marketplace',
]);

/**
 * Optional harness discriminator. v0.7 registries omit this field; the resolver
 * treats omission as `claude-code` for backwards compatibility. v0.8+ codex
 * entries set it to `'codex'` explicitly.
 */
export const GlobalsHarnessEnum = z.enum(['claude-code', 'codex']);
export type GlobalsHarness = z.infer<typeof GlobalsHarnessEnum>;

const PluginEntrySchema = z
  .object({
    source: PluginSourceEnum,
    install: z.string().min(1),
    discover_path: z.string().min(1),
    version: z.string().regex(SEMVER_RE).optional(),
    harness: GlobalsHarnessEnum.optional(),
  })
  .strict();

export type GlobalsPluginEntry = z.infer<typeof PluginEntrySchema>;

// MCP entries record only non-secret metadata. We deliberately do NOT capture
// `env` values (stdio MCPs) or `headers` values (http MCPs) from
// `~/.claude.json` — those frequently contain API tokens and would leak if
// committed. `has_env` / `has_headers` are presence flags for documentation
// only; the runtime config stays the source of truth for actual values.
//
// Two transports are supported, modelled as a discriminated union on `type`:
//   - stdio (default): legacy command/args MCPs.
//   - http: `~/.claude.json` entries with `type: "http"` and a `url`.
const StdioMcpEntrySchema = z
  .object({
    source: z.enum(['claude-code-config', 'codex-config']),
    type: z.literal('stdio'),
    command: z.string().min(1),
    args: z.array(z.string()).optional(),
    has_env: z.boolean(),
    discover_path: z.string().min(1),
    harness: GlobalsHarnessEnum.optional(),
  })
  .strict();

const HttpMcpEntrySchema = z
  .object({
    source: z.enum(['claude-code-config', 'codex-config']),
    type: z.literal('http'),
    url: z.string().min(1),
    has_headers: z.boolean(),
    discover_path: z.string().min(1),
    harness: GlobalsHarnessEnum.optional(),
  })
  .strict();

const McpEntrySchema = z.discriminatedUnion('type', [
  StdioMcpEntrySchema,
  HttpMcpEntrySchema,
]);

export type GlobalsMcpStdioEntry = z.infer<typeof StdioMcpEntrySchema>;
export type GlobalsMcpHttpEntry = z.infer<typeof HttpMcpEntrySchema>;
export type GlobalsMcpEntry = z.infer<typeof McpEntrySchema>;
export type MCPRegistryEntry = GlobalsMcpEntry;

const HookEntrySchema = z
  .object({
    source: z.literal('claude-code-hooks'),
    discover_path: z.string().min(1),
    harness: GlobalsHarnessEnum.optional(),
  })
  .strict();

export type GlobalsHookEntry = z.infer<typeof HookEntrySchema>;

const NameKeyedRecord = <T extends z.ZodTypeAny>(value: T) =>
  z.record(z.string().regex(NAME_RE, 'name must be kebab-case lowercase'), value);

export const GlobalsRegistrySchema = z
  .object({
    schemaVersion: z.literal(1),
    generated_at: z.string().min(1),
    machine: z.string().min(1),
    plugins: NameKeyedRecord(PluginEntrySchema),
    mcps: NameKeyedRecord(McpEntrySchema),
    hooks: NameKeyedRecord(HookEntrySchema),
  })
  .strict();

export type GlobalsRegistry = z.infer<typeof GlobalsRegistrySchema>;

/**
 * Resolve an entry's effective harness. Pre-v0.8 registries omitted the
 * `harness` field, so we treat undefined as `claude-code` for backwards
 * compatibility — v0.7 registries continue to filter against the claude-code
 * harness only, exactly as before.
 */
export function entryHarness(
  e: { harness?: GlobalsHarness | undefined } | undefined,
): GlobalsHarness {
  return e?.harness ?? 'claude-code';
}
